"""Classify git commits as AI-generated, human, or unknown.

Pure functions over parsed commit data — no git or subprocess I/O lives here.
`blame.py` produces `CommitInfo`; this module decides the `Attribution`.
"""

from __future__ import annotations

import re
from enum import Enum

from pydantic import BaseModel


class Origin(str, Enum):
    AI = "ai"
    HUMAN = "human"
    UNKNOWN = "unknown"


class CommitInfo(BaseModel):
    sha: str
    author_name: str
    author_email: str
    message: str
    trailers: list[tuple[str, str]]


class Attribution(BaseModel):
    origin: Origin
    reason: str
    matched_agent: str | None = None


# Agent signatures. Trailer matches are case-insensitive substring checks
# against the trailer *value*; email matches are case-insensitive substring
# checks against the author email. Each entry is restricted to signals that
# are unambiguous enough to avoid false positives.
AI_AGENTS: dict[str, dict[str, list[str]]] = {
    "claude":  {"trailer": ["claude"],  "email": ["noreply@anthropic.com"]},
    "copilot": {"trailer": ["copilot"], "email": ["@copilot.github.com"]},
    "cursor":  {"trailer": ["cursor"],  "email": ["@cursor.sh", "@cursor.com"]},
    "chatgpt": {"trailer": ["chatgpt"], "email": []},
    "gemini":  {"trailer": ["gemini"],  "email": []},
    "devin":   {"trailer": ["devin"],   "email": ["@cognition.ai"]},
    "aider":   {"trailer": ["aider"],   "email": []},
}

# Body patterns that indicate AI authorship even without a Co-Authored-By
# trailer. Keep these tight — a false positive here labels a human commit
# as AI-generated.
_BODY_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("claude", re.compile(r"Generated with \[Claude Code\]", re.IGNORECASE)),
    ("unknown-ai", re.compile(r"\U0001F916 Generated", re.IGNORECASE)),
    ("cursor", re.compile(r"Co-authored-by:\s*Cursor", re.IGNORECASE)),
    ("copilot", re.compile(r"Generated by Copilot", re.IGNORECASE)),
]

# Recognize "Co-Authored-By" specifically; other trailers are less reliable
# signals of AI authorship.
_COAUTHOR_KEY = re.compile(r"^co-authored-by$", re.IGNORECASE)


def classify(commit: CommitInfo) -> Attribution:
    """Return an Attribution for a commit.

    Precedence:
      1. Co-Authored-By trailer matches an AI agent.
      2. Commit body matches a known AI-generation pattern.
      3. Author email matches an AI agent domain.

    Falls back to HUMAN / "no-signal" if nothing matches and the commit has
    a real SHA. Sentinel SHAs ("", "uncommitted") map to UNKNOWN.
    """
    if commit.sha in ("", "uncommitted"):
        return Attribution(origin=Origin.UNKNOWN, reason="uncommitted")

    # 1. Co-Authored-By trailers
    for key, value in commit.trailers:
        if not _COAUTHOR_KEY.match(key):
            continue
        value_lower = value.lower()
        for agent, sigs in AI_AGENTS.items():
            for needle in sigs["trailer"]:
                if needle in value_lower:
                    return Attribution(
                        origin=Origin.AI,
                        reason=f"trailer:{agent}",
                        matched_agent=agent,
                    )

    # 2. Body patterns
    for agent, pattern in _BODY_PATTERNS:
        if pattern.search(commit.message):
            return Attribution(
                origin=Origin.AI,
                reason=f"body:{agent}",
                matched_agent=agent if agent != "unknown-ai" else None,
            )

    # 3. Author email
    email_lower = commit.author_email.lower()
    for agent, sigs in AI_AGENTS.items():
        for needle in sigs["email"]:
            if needle in email_lower:
                return Attribution(
                    origin=Origin.AI,
                    reason=f"email:{agent}",
                    matched_agent=agent,
                )

    return Attribution(origin=Origin.HUMAN, reason="no-signal")
